name: FOSSA Action
description: Find license compliance and security issues in your applications with FOSSA
author: Solomon Rubin

inputs:
  api-key:
    required: true
  run-test:
    default: true
  container:
    required: false

runs:
  using: node12
  main: dist/index.js

branding:
  icon: 'check-circle'
  color: 'green'
