[tasks.build-dist]
description = 'Build the dist/ version of the program.'
run = '''
yarn build
'''

[tasks.lint]
description = 'Lint the project.'
run = 'yarn lint'

[tasks.lint-fix]
description = 'Lint the project while also auto-fixing things that can be.'
run = 'yarn lint --fix'

[tasks.test-local]
description = 'Use `act` to test locally.'
run = './.stubs/act push -s fossaApiKey=${FOSSA_API_KEY}'

[settings]
node.corepack = true

[tools]
node = "24.14.1"
"npm:eslint" = "latest"
