name: dependabot-automation

on: pull_request
permissions:
  contents: write
  pull-requests: write

jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - run: gh pr review --approve "$PR_URL"
        if: github.actor == 'dependabot[bot]'
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - run: gh pr merge --auto --squash "$PR_URL"
        if: github.actor == 'dependabot[bot]'
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
